# Generated by Django 4.0.3 on 2022-04-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('number', models.IntegerField(default='123', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=400)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('zip', models.IntegerField(max_length=6)),
                ('quantity', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contact', models.IntegerField(max_length=10)),
                ('address', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
