# Generated by Django 4.0.3 on 2022-04-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
