# Generated by Django 4.0.3 on 2022-04-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_orders_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplierlist',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
